version: '3.4'

services:
  sit725t32022team1:
    image: sit725t32022team1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
